spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/hibernate
    username: root
    password: "12345678@"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect  # Uncomment and set the correct dialect for your MySQL version
    hibernate:
      ddl-auto: update  # This will update the schema, but not drop/create tables
    show-sql: true  # Enables printing SQL queries to the console
